// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqSqRq5zdt2x1BtWShH5I93t3hLtevwdo',
    appId: '1:1025519946092:web:3b2d71e2ede3b675e74b49',
    messagingSenderId: '1025519946092',
    projectId: 'studyquest-4290d',
    authDomain: 'studyquest-4290d.firebaseapp.com',
    storageBucket: 'studyquest-4290d.firebasestorage.app',
    measurementId: 'G-X93KF92PYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpTGbBse9Q1q0rOZnWKuAFKz4uMkKRpps',
    appId: '1:1025519946092:android:f426abf836d2cccae74b49',
    messagingSenderId: '1025519946092',
    projectId: 'studyquest-4290d',
    storageBucket: 'studyquest-4290d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA28xj8f3IMWvcsWNzWU-jxPGbfLJCCbWA',
    appId: '1:1025519946092:ios:b71000a8f6a05489e74b49',
    messagingSenderId: '1025519946092',
    projectId: 'studyquest-4290d',
    storageBucket: 'studyquest-4290d.firebasestorage.app',
    iosBundleId: 'com.example.studyquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA28xj8f3IMWvcsWNzWU-jxPGbfLJCCbWA',
    appId: '1:1025519946092:ios:b71000a8f6a05489e74b49',
    messagingSenderId: '1025519946092',
    projectId: 'studyquest-4290d',
    storageBucket: 'studyquest-4290d.firebasestorage.app',
    iosBundleId: 'com.example.studyquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqSqRq5zdt2x1BtWShH5I93t3hLtevwdo',
    appId: '1:1025519946092:web:0613780f76ba39dbe74b49',
    messagingSenderId: '1025519946092',
    projectId: 'studyquest-4290d',
    authDomain: 'studyquest-4290d.firebaseapp.com',
    storageBucket: 'studyquest-4290d.firebasestorage.app',
    measurementId: 'G-EV4L3RFPF5',
  );

}